import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const user = useUser();

  if (!user) return null;

  return (
    <div className="flex w-full gap-3">
      <img
        src={user.user?.profileImageUrl}
        alt=""
        className="h-14 w-14 rounded-full"
      />
      <input
        placeholder="Type something"
        className="grow bg-transparent outline-none"
      />
    </div>
  );
};
export default function Home() {
  const user = useUser();

  const { data } = api.posts.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex- flex min-h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-3xl">
          <div>
            {user.isSignedIn ? (
              <>
                <SignOutButton /> <CreatePostWizard />
              </>
            ) : (
              <SignInButton />
            )}
          </div>
          {data?.map((post) => (
            <div key={post.id}>{post.content}</div>
          ))}
        </div>
      </main>
    </>
  );
}
